/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guide: [
    {
      type: 'category',
      label: '入门指南',
      link: { type: 'doc', id: 'guide/build-guide' },
      items: [
        'guide/build-guide',
        'guide/architecture-design',
        'guide/development-guide',
        'guide/device-tree',
      ],
    },
  ],
  command: [
    'command/aplay',
    'command/autoshell',
    'command/cat',
    'command/cd',
    'command/clear',
    'command/clk',
    'command/date',
    'command/dcp',
    'command/delay',
    'command/earth',
    'command/echo',
    'command/event',
    'command/go',
    'command/help',
    'command/iplay',
    'command/ls',
    'command/md',
    'command/mkdir',
    'command/mw',
    'command/net',
    'command/ntpdate',
    'command/pwd',
    'command/reboot',
    'command/rm',
    'command/setting',
    'command/shutdown',
    'command/standby',
    'command/sync',
    'command/test',
    'command/tscal',
    'command/uniqueid',
    'command/version',
    'command/write',
  ],
  libx: [
    'libx/aes128',
    'libx/aes256',
    'libx/backoff-strategy',
    'libx/base64',
    'libx/bcd-encoding',
    'libx/biquad-filter',
    'libx/breathing-light',
    'libx/byteorder-conversion',
    'libx/charset',
    'libx/complex-number',
    'libx/arctangent-lookup-table',
    'libx/cosine-lookup-table',
    'libx/crc8',
    'libx/crc16',
    'libx/crc32',
    'libx/device-tree',
    'libx/div',
    'libx/dynamic-buffer',
    'libx/dynamic-string',
    'libx/easing-function',
    'libx/ecdsa256',
    'libx/ewma',
    'libx/fft',
    'libx/fifo',
    'libx/hash-map',
    'libx/hexdump',
    'libx/initcall',
    'libx/integer-square-root',
    'libx/interleaver',
    'libx/json',
    'libx/kalman',
    'libx/key-filter',
    'libx/kobj-virtual-filesystem',
    'libx/lru',
    'libx/mean-filter',
    'libx/median-filter',
    'libx/path',
    'libx/pubsub-system',
    'libx/qrcgen',
    'libx/queue',
    'libx/rbtree',
    'libx/rc4',
    'libx/reed-solomon-error-correction',
    'libx/sha1',
    'libx/sha256',
    'libx/simple-argument-parser',
    'libx/sorted-list',
    'libx/spring-animation',
    'libx/string-hash',
    'libx/touchscreen-filter',
    'libx/unaligned-access',
    'libx/uri-parser',
    'libx/uuid-generator',
    'libx/vm-encryption',
    'libx/window-function',
    'libx/xdef',
    'libx/yuv-color-conversion',
  ],
  subsystems: [
    {
      type: 'category',
      label: '音频子系统',
      link: { type: 'doc', id: 'audio/overview' },
      items: [
        'audio/overview',
        'audio/audio-frame',
        'audio/audio-source',
        'audio/audio-mixer',
        'audio/audio-effect',
        'audio/effect-plugins',
        'audio/audio-sink',
        'audio/usage-examples',
        'audio/extending',
      ],
    },
    {
      type: 'category',
      label: '图形子系统',
      items: [
        'graphic/color',
        'graphic/region',
        'graphic/transform-matrix',
        'graphic/dirty-rectangle',
        'graphic/blur',
        'graphic/Surface',
        'graphic/shape-drawing',
        'graphic/visual-effect',
        'graphic/filter',
      ],
    },
    {
      type: 'category',
      label: '视觉子系统',
      items: [
        'vision/core-types',
        'vision/arithmetic-operations',
        'vision/color-conversion',
        'vision/morphological-operations',
        'vision/dither',
        'vision/thresholding',
        'vision/geometric-transform',
        'vision/drawing',
      ],
    },
    {
      type: 'category',
      label: '字体系统',
      items: [
        'font/font-system',
      ],
    },
    {
      type: 'category',
      label: '内核工具',
      items: [
        'kernel/profiler',
      ],
    },
  ],
  package: [
    'package/libc',
    'package/libcjson',
    'package/libm',
    'package/plmpeg',
    'package/vww',
    'package/xaf',
    'package/xui',
  ],
  driver: [
    'driver/adc',
    'driver/atnet',
    'driver/atomic',
    'driver/audiocapture',
    'driver/audioplayback',
    'driver/battery',
    'driver/block',
    'driver/buzzer',
    'driver/camera',
    'driver/clk',
    'driver/clockevent',
    'driver/clocksource',
    'driver/compass',
    'driver/console',
    'driver/dac',
    'driver/dma',
    'driver/framebuffer',
    'driver/g2d',
    'driver/gmeter',
    'driver/gnss',
    'driver/gpio',
    'driver/gyroscope',
    'driver/hygrometer',
    'driver/i2c',
    'driver/input',
    'driver/interrupt',
    'driver/led',
    'driver/ledstrip',
    'driver/ledtrigger',
    'driver/light',
    'driver/limiter',
    'driver/motor',
    'driver/net',
    'driver/nvmem',
    'driver/oximeter',
    'driver/pressure',
    'driver/printer',
    'driver/proximity',
    'driver/pwm',
    'driver/regulator',
    'driver/reset',
    'driver/rng',
    'driver/rtc',
    'driver/sd',
    'driver/servo',
    'driver/spi',
    'driver/spinlock',
    'driver/stepper',
    'driver/thermometer',
    'driver/uart',
    'driver/vibrator',
    'driver/watchdog',
  ],
};

module.exports = sidebars;
